[ja]
languageName = "日本語"
languageCode = "ja-jp"
contentDir = "content/japanese"
weight = 1

[ja.params]
home = "ホーム"

[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

[en.params]
home = "Home"
