################### Japanese navigation ####################

[[main]]
name = "研究室概要"
url = "overview/"
weight = 1

[[main]]
name = "研究"
url = "research/"
weight = 2

[[main]]
name = "メンバー"
url = "members/"
weight = 3

[[main]]
name = "業績"
url = "publications/"
weight = 4

[[main]]
name = "お知らせ"
url = "notice/"
weight = 5

[[main]]
name = "研究を希望される方へ"
url = "join/"
weight = 6

[[main]]
name = "アクセス"
url = "access/"
weight = 7

[[main]]
name = "お問い合わせ"
url = "https://forms.gle/27n7coB55JCUKAwFA"
weight = 8

# footer menu
[[footer]]
name = "研究室概要"
url = "overview/"

[[footer]]
name = "研究"
url = "research/"

[[footer]]
name = "メンバー"
url = "members/"

[[footer]]
name = "業績"
url = "publications/"

[[footer]]
name = "お問い合わせ"
url = "https://forms.gle/27n7coB55JCUKAwFA"
